version: '3'

services:
  message-service:
    container_name: message-service
    build:
      context: ./MessageService
    ports:
      - "8000:8000"
    networks:
      - app-network

  account-service:
    container_name: account-service
    build:
      context: ./AccountService
    ports:
      - "8001:8001"
    networks:
      - app-network

  client:
    container_name: client-service
    build:
      context: ./ColabTool
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
